import { defineField, defineType } from 'sanity';

const text = (
  name: string,
  title: string,
  description: string,
  group: string,
  initialValue?: string,
) =>
  defineField({
    name,
    title,
    type: 'string',
    description,
    group,
    initialValue,
  });

const portableText = (
  name: string,
  title: string,
  description: string,
  group: string,
) =>
  defineField({
    name,
    title,
    type: 'array',
    description,
    group,
    of: [
      {
        type: 'block',
        styles: [
          { title: 'Normal', value: 'normal' },
          { title: 'Heading 3', value: 'h3' },
        ],
        marks: {
          decorators: [
            { title: 'Strong', value: 'strong' },
            { title: 'Italic', value: 'em' },
          ],
          annotations: [
            {
              name: 'link',
              type: 'object',
              title: 'Link',
              fields: [{ name: 'href', type: 'url', title: 'URL' }],
            },
          ],
        },
      },
    ],
  });

export const bookingCopy = defineType({
  name: 'bookingCopy',
  title: 'Booking Copy',
  type: 'document',
  description:
    'Every visible string in the booking surface — wizard, success page, cancel pages, emails, and admin. Use {placeholder} tokens where noted; supported tokens are listed per-field.',
  groups: [
    { name: 'wizard', title: 'Wizard', default: true },
    { name: 'steps', title: 'Steps' },
    { name: 'errors', title: 'Errors' },
    { name: 'success', title: 'Success' },
    { name: 'cancel', title: 'Cancel' },
    { name: 'emails', title: 'Emails' },
    { name: 'admin', title: 'Admin' },
  ],
  fields: [
    // ── Wizard ──────────────────────────────────────────
    text('wizardPageTitle', 'Page title', 'Browser tab title.', 'wizard', 'Reserve Your Experience'),
    text(
      'wizardPageMetaDescription',
      'Meta description',
      'For search engines and social shares.',
      'wizard',
      'Reserve your appointment online with Atelier Lumière.',
    ),
    text('wizardHeadlineEyebrow', 'Headline eyebrow', 'Small label above the headline.', 'wizard', 'Reservations'),
    text('wizardHeadlineMain', 'Headline (main)', 'First part of the headline.', 'wizard', 'Reserve Your'),
    text('wizardHeadlineItalic', 'Headline (italic)', 'Italic / accent word at the end of the headline.', 'wizard', 'Experience'),
    portableText(
      'wizardIntro',
      'Wizard intro',
      'Short paragraph below the headline. Supports bold, italic, links.',
      'wizard',
    ),
    text(
      'wizardWelcomeBackTemplate',
      'Welcome-back greeting',
      'Shown when a returning customer is recognized via cookie. Supports {firstName}.',
      'wizard',
      'Welcome back, {firstName} ✓',
    ),
    text(
      'wizardNotYouLink',
      'Not-you reset link',
      'Link to clear recognition. Supports {firstName}.',
      'wizard',
      'Not {firstName}? Use different details',
    ),
    portableText(
      'wizardPolicyAcceptText',
      'Policy summary',
      'Shown above the Pay button. Should summarize the cancellation policy.',
      'wizard',
    ),

    // ── Steps ───────────────────────────────────────────
    text('stepsServiceLabel', 'Step label: Service', '', 'steps', 'Service'),
    text('stepsTechnicianLabel', 'Step label: Technician', '', 'steps', 'Technician'),
    text('stepsDateTimeLabel', 'Step label: Date & Time', '', 'steps', 'Date & Time'),
    text('stepsDetailsLabel', 'Step label: Details', '', 'steps', 'Details'),
    text('stepsReviewLabel', 'Step label: Review', '', 'steps', 'Review'),

    text('serviceHeading', 'Service step heading', '', 'steps', 'Choose a Service'),
    text('serviceSubHeading', 'Service step subheading', 'Optional sub-line.', 'steps', ''),
    text('servicePriceFromLabel', 'Service price prefix', '', 'steps', 'from'),
    text('serviceDepositLabel', 'Deposit label', '', 'steps', 'Deposit at booking'),
    text('serviceBalanceLabel', 'Balance label', '', 'steps', 'Balance due in salon'),
    text(
      'serviceDurationLabel',
      'Duration display',
      'Supports {minutes}.',
      'steps',
      '{minutes} min',
    ),
    text(
      'serviceEmptyState',
      'Empty state — no services',
      '',
      'steps',
      'No services available right now.',
    ),

    text('techHeading', 'Technician step heading', '', 'steps', 'Choose Your Technician'),
    text(
      'techSubHeading',
      'Technician step subheading',
      'Supports {service}.',
      'steps',
      'Each artist below is qualified for {service}.',
    ),
    text('techAnyTechLabel', 'No-preference label', '', 'steps', 'No Preference'),
    text(
      'techAnyTechDescription',
      'No-preference description',
      '',
      'steps',
      "We'll match you with our most-available artist.",
    ),
    text('techSpecialtyLabel', 'Specialty label', '', 'steps', 'Specialty'),
    text(
      'techEmptyState',
      'Empty state — no qualified techs',
      '',
      'steps',
      'No technicians qualified for this service.',
    ),

    text('dateTimeDateHeading', 'Date heading', '', 'steps', 'Select Date'),
    text('dateTimeTimeHeading', 'Time heading', '', 'steps', 'Preferred Time'),
    text(
      'dateTimeMonthFormat',
      'Month label format',
      'Supports {month} and {year}.',
      'steps',
      '{month} {year}',
    ),
    defineField({
      name: 'dateTimeWeekdayShort',
      title: 'Weekday letters',
      type: 'array',
      description: 'Seven entries starting Sunday. Single letters work best.',
      group: 'steps',
      of: [{ type: 'string' }],
      initialValue: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
      validation: (Rule) => Rule.length(7),
    }),
    text(
      'dateTimeNoSlotsThisDay',
      'No-slots message',
      '',
      'steps',
      'No availability — try another day.',
    ),
    text(
      'dateTimeMinHoursBufferNote',
      'Min-hours buffer note',
      'Supports {hours}.',
      'steps',
      'Same-day bookings need {hours}h notice.',
    ),
    text(
      'dateTimeTimezoneNote',
      'Timezone note',
      'Reassures customer about which timezone times are shown in.',
      'steps',
      'All times shown in NZT.',
    ),

    text('detailsHeading', 'Details step heading', '', 'steps', 'Your Details'),
    text('detailsSubHeading', 'Details step subheading', '', 'steps', ''),
    text('detailsNameLabel', 'Name label', '', 'steps', 'Name'),
    text('detailsNamePlaceholder', 'Name placeholder', '', 'steps', 'Full name'),
    text('detailsPhoneLabel', 'Phone label', '', 'steps', 'Phone'),
    text('detailsPhonePlaceholder', 'Phone placeholder', '', 'steps', 'e.g. 022 123 4567'),
    text('detailsEmailLabel', 'Email label', '', 'steps', 'Email'),
    text('detailsEmailPlaceholder', 'Email placeholder', '', 'steps', 'your@email.com'),
    text('detailsNotesLabel', 'Notes label', '', 'steps', 'Special requests'),
    text(
      'detailsNotesPlaceholder',
      'Notes placeholder',
      '',
      'steps',
      'Any allergies, design preferences, or special requests…',
    ),
    text(
      'detailsEmailOptionalSuffix',
      'Optional suffix',
      'Suffix used to mark optional fields.',
      'steps',
      '(optional)',
    ),
    text(
      'detailsRequiredFieldIndicator',
      'Required indicator',
      'Symbol next to required field labels.',
      'steps',
      '*',
    ),

    text('reviewHeading', 'Review step heading', '', 'steps', 'Review Your Booking'),
    text('reviewServiceLabel', 'Review label: Service', '', 'steps', 'Service'),
    text('reviewTechnicianLabel', 'Review label: Technician', '', 'steps', 'Technician'),
    text('reviewDateLabel', 'Review label: Date', '', 'steps', 'Date'),
    text('reviewTimeLabel', 'Review label: Time', '', 'steps', 'Time'),
    text('reviewDepositDueLabel', 'Deposit due now', '', 'steps', 'Pay now'),
    text('reviewBalanceDueLabel', 'Balance label', '', 'steps', 'Pay at appointment'),
    text(
      'reviewPayButtonLabel',
      'Pay button',
      'Supports {amount}.',
      'steps',
      'Pay {amount} deposit & confirm',
    ),
    text(
      'reviewPayingProcessingLabel',
      'Processing label',
      'Shown briefly while redirecting to Stripe.',
      'steps',
      'Redirecting to secure payment…',
    ),

    // ── Errors ──────────────────────────────────────────
    text(
      'errorsSlotJustTaken',
      'Slot just taken',
      '',
      'errors',
      'That slot was just booked — please pick another.',
    ),
    text(
      'errorsScheduleChanged',
      'Schedule changed',
      '',
      'errors',
      "The technician's schedule has changed. Please pick a new time.",
    ),
    text(
      'errorsNetworkError',
      'Network error',
      '',
      'errors',
      'Connection problem — please try again.',
    ),
    text(
      'errorsRateLimited',
      'Rate limited',
      '',
      'errors',
      'Too many attempts — please wait a moment and try again.',
    ),
    text(
      'errorsCaptchaFailed',
      'Captcha failed',
      '',
      'errors',
      "We couldn't verify you're human. Please refresh and try again.",
    ),
    text(
      'errorsGeneric',
      'Generic error',
      'Fallback when no specific error message applies.',
      'errors',
      'Something went wrong. Please try again or call us.',
    ),

    // ── Navigation ──────────────────────────────────────
    text('navBack', 'Back button', '', 'wizard', 'Back'),
    text('navNext', 'Next button', '', 'wizard', 'Next'),
    text('navCancelWizard', 'Cancel wizard', '', 'wizard', 'Cancel booking'),

    // ── Success ─────────────────────────────────────────
    text('successHeading', 'Success heading', '', 'success', "You're booked"),
    text(
      'successSubheading',
      'Success subheading',
      'Supports {firstName}.',
      'success',
      "We can't wait to see you, {firstName}.",
    ),
    portableText(
      'successBodyTemplate',
      'Success body',
      'Supports {service}, {tech}, {date}, {time}, {address}, {balance}, {firstName}.',
      'success',
    ),
    text(
      'successCalendarButtonLabel',
      'Add-to-calendar button',
      '',
      'success',
      'Add to calendar',
    ),
    text(
      'successEmailSentNote',
      'Email sent note',
      'Supports {email}.',
      'success',
      "We've sent a confirmation to {email}.",
    ),
    portableText(
      'successCancellationNote',
      'Cancellation note',
      'Supports {cancelLink}, {phone}, {cutoffHours}. Place {cancelLink} as a link annotation in the rich text.',
      'success',
    ),

    // ── Cancel ──────────────────────────────────────────
    text('cancelHeading', 'Cancel heading', '', 'cancel', 'Cancel your booking'),
    portableText(
      'cancelConfirmBody',
      'Cancel confirm body',
      'Supports {service}, {tech}, {date}, {time}, {refundAmount}.',
      'cancel',
    ),
    text(
      'cancelConfirmButton',
      'Confirm cancel button',
      'Supports {refundAmount}.',
      'cancel',
      'Yes, cancel and refund {refundAmount}',
    ),
    text(
      'cancelSuccessHeading',
      'Cancel success heading',
      '',
      'cancel',
      'Cancellation confirmed',
    ),
    portableText(
      'cancelSuccessBody',
      'Cancel success body',
      'Supports {refundAmount}, {firstName}.',
      'cancel',
    ),
    text(
      'cancelTooLateHeading',
      'Inside cutoff heading',
      '',
      'cancel',
      'Inside cancellation window',
    ),
    portableText(
      'cancelTooLateBody',
      'Inside cutoff body',
      'Supports {phone}, {cutoffHours}.',
      'cancel',
    ),
    text(
      'cancelAlreadyUsedHeading',
      'Already-cancelled heading',
      '',
      'cancel',
      'Already cancelled',
    ),
    portableText(
      'cancelAlreadyUsedBody',
      'Already-cancelled body',
      '',
      'cancel',
    ),

    // ── Emails ──────────────────────────────────────────
    text(
      'emailConfirmationSubjectTemplate',
      'Confirmation email — subject',
      'Supports {service}, {date}, {time}, {firstName}.',
      'emails',
      'Your booking is confirmed — {service} on {date}',
    ),
    text(
      'emailConfirmationHeroHeadline',
      'Confirmation email — hero',
      '',
      'emails',
      "You're booked",
    ),
    portableText(
      'emailConfirmationBodyIntro',
      'Confirmation email — intro',
      'Supports {firstName}, {service}, {tech}, {date}, {time}.',
      'emails',
    ),
    text(
      'emailConfirmationDetailsHeading',
      'Confirmation email — details heading',
      '',
      'emails',
      'Appointment details',
    ),
    text(
      'emailConfirmationBalanceNote',
      'Confirmation email — balance note',
      'Supports {balance}.',
      'emails',
      'Balance of {balance} due at appointment.',
    ),
    text(
      'emailConfirmationCancellationHeading',
      'Confirmation email — cancellation heading',
      '',
      'emails',
      'Need to cancel?',
    ),
    portableText(
      'emailConfirmationCancellationBody',
      'Confirmation email — cancellation body',
      'Supports {cancelLink} (use as link annotation), {phone}, {cutoffHours}.',
      'emails',
    ),
    portableText('emailConfirmationSignoff', 'Confirmation email — signoff', '', 'emails'),
    text(
      'emailOwnerNotificationSubjectTemplate',
      'Owner notification — subject',
      'Supports {customer}, {date}, {time}, {service}, {tech}.',
      'emails',
      'New booking — {customer} — {date} {time}',
    ),
    text(
      'emailOwnerNotificationHeading',
      'Owner notification — heading',
      '',
      'emails',
      'New booking received',
    ),
    portableText(
      'emailOwnerNotificationBody',
      'Owner notification — body',
      'Supports {customer}, {customerPhone}, {customerEmail}, {service}, {serviceDuration}, {tech}, {date}, {time}, {deposit}, {amount}, {balance}, {notes}, {visitCount}, {adminLink}.',
      'emails',
    ),
    text(
      'emailCancellationSubjectTemplate',
      'Cancellation email — subject',
      'Supports {service}, {date}.',
      'emails',
      'Your booking has been cancelled',
    ),
    text(
      'emailCancellationHeading',
      'Cancellation email — heading',
      '',
      'emails',
      'Booking cancelled',
    ),
    portableText(
      'emailCancellationBody',
      'Cancellation email — body',
      'Supports {firstName}, {refundAmount}, {service}, {date}.',
      'emails',
    ),
    text(
      'emailCancellationNoRefundSubjectTemplate',
      'Cancellation (no refund) — subject',
      '',
      'emails',
      'Your booking has been cancelled',
    ),
    text(
      'emailCancellationNoRefundHeading',
      'Cancellation (no refund) — heading',
      '',
      'emails',
      'Booking cancelled',
    ),
    portableText(
      'emailCancellationNoRefundBody',
      'Cancellation (no refund) — body',
      'Supports {firstName}, {service}, {date}.',
      'emails',
    ),
    text(
      'emailRescheduleSubjectTemplate',
      'Reschedule email — subject',
      'Supports {service}, {newDate}, {newTime}.',
      'emails',
      'Your booking has been rescheduled — {newDate}',
    ),
    text(
      'emailRescheduleHeading',
      'Reschedule email — heading',
      '',
      'emails',
      'Your booking has been rescheduled',
    ),
    portableText(
      'emailRescheduleBody',
      'Reschedule email — body',
      'Supports {firstName}, {service}, {oldDate}, {oldTime}, {newDate}, {newTime}, {tech}, {phone}.',
      'emails',
    ),
    text(
      'emailReviewSubjectTemplate',
      'Review email — subject',
      'Sent 2 days after appointment. Supports {service}, {tech}, {firstName}.',
      'emails',
      'How was your visit, {firstName}?',
    ),
    text(
      'emailReviewHeading',
      'Review email — heading',
      '',
      'emails',
      'Thank you for visiting Atelier Lumière',
    ),
    portableText(
      'emailReviewBody',
      'Review email — body',
      'Supports {firstName}, {service}, {tech}, {reviewLink}.',
      'emails',
    ),
    text(
      'reviewLinkUrl',
      'Review link URL',
      'Where the "leave a review" button in the review email points. Usually the salon\'s Google review URL.',
      'emails',
      '',
    ),
    text(
      'smsReminderTemplate',
      'SMS reminder body',
      'Sent ~24h before the appointment. Keep under 320 characters. Supports {firstName}, {service}, {tech}, {date}, {time}.',
      'emails',
      'Hi {firstName}, reminder of your {service} with {tech} tomorrow at {time}. To cancel/change, please call us. — Atelier Lumière',
    ),

    // ── Admin ───────────────────────────────────────────
    text('adminDashboardTitle', 'Admin: dashboard title', '', 'admin', 'Booking Admin'),
    text('adminBookingsTitle', 'Admin: bookings page title', '', 'admin', 'Bookings'),
    text('adminCustomersTitle', 'Admin: customers page title', '', 'admin', 'Customers'),
    text('adminRefundsTitle', 'Admin: refunds page title', '', 'admin', 'Refunds'),
    text('adminSignOutLabel', 'Admin: sign out', '', 'admin', 'Sign out'),
    text(
      'adminRefundConfirmationPrompt',
      'Refund confirm prompt',
      'Supports {customerName}.',
      'admin',
      "To confirm, type the customer's first name ({customerName}) below.",
    ),
    text(
      'adminRefundButtonTemplate',
      'Refund button',
      'Supports {amount}.',
      'admin',
      'Refund {amount}',
    ),
    text(
      'adminCancelConfirmationPrompt',
      'Cancel-no-refund prompt',
      '',
      'admin',
      'Type CANCEL to confirm cancellation without refund.',
    ),
    defineField({
      name: 'adminBookingStatusLabels',
      title: 'Booking status labels',
      type: 'object',
      description: 'Display labels for each booking status enum value.',
      group: 'admin',
      fields: [
        defineField({
          name: 'pending_payment',
          type: 'string',
          title: 'pending_payment',
          initialValue: 'Pending payment',
        }),
        defineField({
          name: 'confirmed',
          type: 'string',
          title: 'confirmed',
          initialValue: 'Confirmed',
        }),
        defineField({
          name: 'cancelled',
          type: 'string',
          title: 'cancelled',
          initialValue: 'Cancelled',
        }),
        defineField({
          name: 'completed',
          type: 'string',
          title: 'completed',
          initialValue: 'Completed',
        }),
        defineField({
          name: 'expired',
          type: 'string',
          title: 'expired',
          initialValue: 'Expired',
        }),
      ],
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Booking Copy' };
    },
  },
});
